"""PDF report generation. REQ-17.

Two documents, with the exact field sets listed in SRS Appendix B: a Case
Report (what happened) and a Recovery Report (what is owed and what came
back). They are built to be printed and handed to a bank, a police station or
the RBI Ombudsman, so every page carries the case reference and the legal
disclaimer required by SRS section 7.
"""
import io
from datetime import UTC, datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.evidence import Evidence
from app.models.recovery import RecoveryRequest
from app.models.report import Case, ScamReport
from app.models.user import User

DISCLAIMER = (
    "This report is generated by FSDIRAS, an assistive platform. It does not "
    "guarantee recovery of lost funds and does not replace filing an official "
    "complaint with the police or the National Cyber Crime Reporting Portal "
    "(cybercrime.gov.in). Any risk score shown is advisory and was produced by "
    "an automated model; it is not a determination of fraud."
)

_LABEL_WIDTH = 55 * mm
_VALUE_WIDTH = 105 * mm


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "FsdirasTitle", parent=base["Title"], fontSize=16, spaceAfter=2 * mm
        ),
        "heading": ParagraphStyle(
            "FsdirasHeading",
            parent=base["Heading2"],
            fontSize=11,
            spaceBefore=6 * mm,
            spaceAfter=2 * mm,
        ),
        "body": base["BodyText"],
        "small": ParagraphStyle(
            "FsdirasSmall", parent=base["BodyText"], fontSize=7.5, textColor=colors.grey
        ),
    }


def _field_table(rows: list[tuple[str, str]], styles: dict) -> Table:
    data = [[Paragraph(f"<b>{label}</b>", styles["body"]), Paragraph(value, styles["body"])]
            for label, value in rows]
    table = Table(data, colWidths=[_LABEL_WIDTH, _VALUE_WIDTH])
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("LINEBELOW", (0, 0), (-1, -2), 0.25, colors.HexColor("#DDDDDD")),
            ]
        )
    )
    return table


def _money(value: float | None) -> str:
    """Indian rupee formatting; the audience is Indian banks and police."""
    return f"Rs. {float(value or 0):,.2f}"


def _build(story: list, title: str, subtitle: str, styles: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        title=title,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )

    header = [
        Paragraph(title, styles["title"]),
        Paragraph(subtitle, styles["small"]),
        Spacer(1, 4 * mm),
    ]
    footer = [
        Spacer(1, 8 * mm),
        Paragraph(f"<b>Disclaimer.</b> {DISCLAIMER}", styles["small"]),
    ]

    doc.build(header + story + footer)
    return buffer.getvalue()


def case_report(
    *,
    case: Case,
    report: ScamReport,
    evidence: list[Evidence],
    investigator: User | None,
) -> bytes:
    """Appendix B, Case Report column."""
    styles = _styles()
    generated = datetime.now(UTC).strftime("%d %b %Y, %H:%M UTC")

    risk = (
        f"{report.risk_score} / 100 ({str(report.risk_band).replace('_', ' ').title()}) "
        "-- advisory"
        if report.risk_score is not None
        else "Not scored"
    )

    story = [
        _field_table(
            [
                ("Case ID", case.case_ref),
                ("Report ID", report.report_ref),
                ("Reporter Name", report.reporter_name),
                ("Reporter Contact", report.reporter_contact),
                ("Scam Category", str(report.category).replace("_", " ").title()),
                ("Report Date", report.report_date.strftime("%d %b %Y")),
                ("Risk Score", risk),
                (
                    "Investigator Assigned",
                    investigator.full_name if investigator else "Not yet assigned",
                ),
                ("Case Status", str(case.status).replace("_", " ").title()),
                ("Amount Reported Lost", _money(report.amount_involved)),
            ],
            styles,
        ),
        Paragraph("Incident description", styles["heading"]),
        Paragraph(report.description, styles["body"]),
        Paragraph("Evidence list", styles["heading"]),
    ]

    if evidence:
        rows = [["#", "File", "Type", "Size", "SHA-256 (first 16)"]]
        for index, item in enumerate(evidence, start=1):
            rows.append(
                [
                    str(index),
                    item.filename + (" (archived)" if item.is_archived else ""),
                    item.content_type,
                    f"{item.size_bytes / 1024:.1f} KB",
                    item.sha256[:16],
                ]
            )
        table = Table(rows, colWidths=[10 * mm, 55 * mm, 32 * mm, 22 * mm, 41 * mm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F0F0")),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#CCCCCC")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        story.append(table)
        # The digests are printed so a recipient can verify the attached files
        # independently -- that is the point of a chain of custody.
        story.append(Spacer(1, 2 * mm))
        story.append(
            Paragraph(
                "Digests are printed so the recipient can verify each file "
                "against the copy supplied to them.",
                styles["small"],
            )
        )
    else:
        story.append(Paragraph("No evidence has been submitted for this case.", styles["body"]))

    return _build(
        story,
        "Case Report",
        f"FSDIRAS - Project ID 35 | Case {case.case_ref} | Generated {generated}",
        styles,
    )


def recovery_report(
    *, case: Case, report: ScamReport, recovery: RecoveryRequest
) -> bytes:
    """Appendix B, Recovery Report column."""
    styles = _styles()
    generated = datetime.now(UTC).strftime("%d %b %Y, %H:%M UTC")

    outstanding = float(recovery.amount_reported or 0) - float(recovery.amount_recovered or 0)

    story = [
        _field_table(
            [
                ("Case ID", case.case_ref),
                ("Reporter Name", report.reporter_name),
                ("Account Number", recovery.account_number or "Not provided"),
                ("Bank Name", recovery.bank_name or "Not provided"),
                ("IFSC Code", recovery.ifsc_code or "Not provided"),
                ("Amount Reported", _money(recovery.amount_reported)),
                ("Amount Recovered", _money(recovery.amount_recovered)),
                ("Outstanding", _money(outstanding)),
                ("Recovery Status", str(recovery.status).replace("_", " ").title()),
                ("Remarks", recovery.remarks or "-"),
            ],
            styles,
        ),
    ]

    return _build(
        story,
        "Recovery Assistance Report",
        f"FSDIRAS - Project ID 35 | Case {case.case_ref} | Generated {generated}",
        styles,
    )
